[relaychain]
default_command = "../infrablockchain-substrate/target/release/infra-relaychain"
chain = "infra-relay-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1200
chain = "local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/infra-parachain-template-node"
	args = ["-lparachain=debug", "--alice"]