# If the author of the issues is not a contributor to the project, label
# the issue with 'Z0-unconfirmed'

name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
    - name: Install tooling
      run: sudo apt-get install -y protobuf-compiler
    - name: Add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --release
    